about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('',views.about, name= "about"),
]

ape/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
     path('services/', include('services.urls')),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('research/', include('research.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
 
app_name='blog' 
urlpatterns = [
    path('', views.blog, name='blog'),
    path('<slug:slug>', views.blogView, name='blog_details'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('',views.contact, name= "contact"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
]

templates/includes/footer.html
{% load static %}
<section class="bg-primary mt-20 py-20 px-4 font-title md:px-4 2xl:px-0" >
    <div class="max-w-screen-xl  mx-auto">
        <div class="flex flex-col gap-6 w-full justify-between md:flex-row  " >
            <div class="w-full  flex flex-col">
                <a href="#" class="flex">
                    <svg class="h-10 mr-3" width="51" height="70" viewBox="0 0 51 70" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)"><path d="M1 53H27.9022C40.6587 53 51 42.7025 51 30H24.0978C11.3412 30 1 40.2975 1 53Z" fill="#76A9FA"></path><path d="M-0.876544 32.1644L-0.876544 66.411C11.9849 66.411 22.4111 55.9847 22.4111 43.1233L22.4111 8.87674C10.1196 8.98051 0.518714 19.5571 -0.876544 32.1644Z" fill="#A4CAFE"></path><path d="M50 5H23.0978C10.3413 5 0 15.2975 0 28H26.9022C39.6588 28 50 17.7025 50 5Z" fill="#1C64F2"></path></g><defs><clipPath id="clip0"><rect width="51" height="70" fill="white"></rect></clipPath></defs></svg>
                        <span class="self-center text-4xl text-white font-semibold whitespace-nowrap">Website</span>
                    </a>
                <p class="mt-3 text-base font-medium text-white md:mt-4 lg:mt-6">
                    Discover the ultimate destination for cutting-edge automotive solutions. From premium parts to expert services, we power your journey with quality, innovation, and performance.
                </p>
                <div class="w-full mt-4">
                    <p class=" text-base font-semibold text-white">
                        Connect With Us:
                    </p>
                    <div class="flex gap-3 mt-3">
                        {% for social in social_links %}
                        <a href="{{ social.url }}" target="_blank" class="text-white hover:text-white transition duration-300 ease-in-out">
                            <img src="{{ social.icon.url }}" alt="{{ social.name }}" class="w-10 h-10">
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="w-full  flex flex-col font-semibold">
                <h3 class="text-2xl text-white mb-4">Contact Us</h3>
                <p class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fas fa-phone"></i> Tell Free: <span class="text-secondary">{{ brand.phone }}</span>
                </p>
                <p class="mt-2 text-base  text-white md:mt-3">
                    <i class="fa-brands fa-whatsapp"></i> Chat Free! <span class="text-secondary p-1 text-sm rounded-md bg-orange-100">Chat now</span>
                </p>
                <p class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fa-solid fa-envelope"></i>Email :{{ brand.email }}
                </p>
            </div>
            <div class="w-full  flex flex-col font-semibold">
                <h3 class="text-2xl text-white mb-4">Quick Links</h3>
                <a href="{% url 'about:about' %}" class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fa-solid fa-caret-right mr-2 text-secondary"></i>About Us
                </a>
                <a href="{% url 'products:category' %}" class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fa-solid fa-caret-right mr-2 text-secondary"></i>Products
                </a>
                <a href="{% url 'services:services' %}" class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fa-solid fa-caret-right mr-2 text-secondary"></i>Services
                </a>
                <a href="{% url 'blog:blog' %}" class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fa-solid fa-caret-right mr-2 text-secondary"></i>Blogs
                </a>
                <a href="{% url 'contact:contact' %}" class="mt-2 text-base  text-white md:mt-3 ">
                    <i class="fa-solid fa-caret-right mr-2 text-secondary"></i>Contact
                </a>
            </div>
            <div class="w-full  flex flex-col font-medium">
                <p class=" text-base  text-white  ">
                    {{brand.address}}
                </p>
                <iframe src="{{brand.googlemap_url}}"
                 width="100%" height="150" class="mt-3 rounded-md" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

            </div>
        </div>
    </div>
</section>
<section class="bg-primary py-5 font-title border-t border-gray-400 flex px-4  md:px-4 2xl:px-0" >
    <div class="max-w-screen-xl text-sm  mx-auto flex flex-col gap-6 w-full justify-between md:flex-row text-gray-400">
        <div class="w-full md:w-1/2 justify-center text-center md:justify-start md:text-start text-gray-400">
            <p>copyright 2025 gideon autmotive industries developed by Ec4you</p>
        </div>
        <div class="w-full md:w-1/2 flex gap-6 justify-center md:justify-end  text-gray-400">
            <p>Privacy Policy</p>
            <p>Terms& conditions</p>
        </div>
    </div>
</section>

templates/includes/header.html
{% load static %}

<!-- This is an example component -->
 <section class="bg-primary py-8 font-title px-4  md:px-4 2xl:px-0" >
<div class="max-w-screen-xl  mx-auto">
    
    <nav class="border-gray-200">
    <div class=" mx-auto flex flex-wrap items-center justify-between">
        <a href="{% url 'home:home' %}" class="flex">
        <img class="w-20" src="{{brand.logo.url}}" alt="Primary Logo">
        </a>
        <button data-collapse-toggle="mobile-menu" type="button" class="md:hidden ml-3 text-gray-400 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300 rounded-lg inline-flex items-center justify-center" aria-controls="mobile-menu-2" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <div class="hidden md:block w-full md:w-auto" id="mobile-menu">
            <ul class="flex-col md:flex-row flex md:space-x-12 mt-4 md:mt-0 md:text-lg md:font-medium">
                <li>
                    <a href="{% url 'home:home' %}" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/' %}text-secondary {% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}" 
                       aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{% url 'about:about' %}" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/about/' %}text-secondary{% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}">
                        About Us
                    </a>
                </li>
                <li>
                    <a href="#" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/services/' %}text-secondary{% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}">
                        Services
                    </a>
                </li>
                <li>
                    <a href="{% url 'products:category' %}" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/products/' %}text-secondary{% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}">
                        Product
                    </a>
                </li>
                <li>
                    <a href="{% url 'research:research' %}" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/research/' %}text-secondary{% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}">
                        Research & Development
                    </a>
                </li>
                <li>
                    <a href="#" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/blog/' %}text-secondary{% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}">
                        Blog
                    </a>
                </li>
                <li>
                    <a href="{% url 'contact:contact' %}" 
                       class="block pl-3 pr-4 py-2 md:p-0 
                              {% if request.path == '/contact/' %}text-secondary{% else %}text-white hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary{% endif %}">
                        Contact
                    </a>
                </li>
            </ul>
            
        </div>
    </div>
    </nav>
</div>
</section>
<script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>