ape/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
     path('services/', include('services.urls')),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('research/', include('research.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
 
app_name='blog' 
urlpatterns = [
    path('', views.blog, name='blog'),
    path('<slug:slug>', views.blogView, name='blog_details'),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils.text import slugify


class Posts(models.Model):

     title=models.CharField(max_length=200 ,)
     slug=models.SlugField(null=True,blank=True, unique=True , allow_unicode=True, max_length=200)
     image=models.ImageField(upload_to='blog/')
     short_desc=models.TextField(max_length=200, blank=True,null=True)
     long_desc=RichTextField() 
     author=models.ForeignKey(User, on_delete=models.CASCADE)
     created_at = models.DateTimeField(auto_now_add=True)
     is_active = models.BooleanField(default=True)


     def save(self, *args,**kwargs):
         if not self.slug:
             self.slug=slugify(self.title)
         super().save(*args,**kwargs)

     def __str__(self):
        return self.title
     

blog/views.py
from django.shortcuts import render
from .models import Posts

def blog(request):
    posts=Posts.objects.all()
    context={
        'posts':posts
    }
    return render(request, 'blog/blog.html', context)

def blogView(request,slug):
    posts=Posts.objects.get(slug=slug)
    related_post=Posts.objects.all()
    context={
        'posts':posts,
        'related_post':related_post

    }
    return render(request, 'blog/blog_detail.html', context)

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blogpage{% endblock %}

{% block content %}

<section class="font-title px-4 md:px-4 2xl:px-0 bg-cover bg-no-repeat w-full h-80 " style = "background-image: url({% static 'images/category-hero.jpg' %});">
    <div class="max-w-screen-xl mx-auto h-full flex flex-col justify-center gap-3">
       <h3 class=" text-white font-medium text-sm md:text-base text-case">Home / <span class="text-secondary">Blog</span></h3>
       <h1 class=" text-white text-2xl font-bold md:text-4xl ">Our Blogs</h1>
    </div>
</section>

<section class="font-title mt-20 px-4 md:px-4 2xl:px-0">
    <div class="max-w-screen-xl mx-auto">
        <h2 class="text-3xl mt-3 text-primary font-semibold md:text-3xl lg:text-4xl xl:text-5xl">Our Latest Blogs and Articles</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 mt-6">
         {% for post in posts %}
                <div class="relative flex flex-col my-6 bg-white shadow-sm border border-slate-200 rounded-lg w-full">
                    <div class="relative h-56 m-2.5 overflow-hidden text-white rounded-md">
                      <img src="{{post.image.url}}" alt="{{post.name}}" />
                    </div>
                    <div class="p-4">
                        <a href="{% url 'blog:blog_details' post.slug %}"><h6 class="mb-2 text-slate-800 hover:text-secondary text-xl font-semibold">
                        {{post.title}}
                      </h6>
                    </a>
                      <p class="text-slate-600 leading-normal font-light">
                        {{ post.short_desc | truncatewords:20 }}
                      </p>
                    </div>
                    <div class="px-4 pb-4 pt-0 mt-2">
                      <a href="{% url 'blog:blog_details' post.slug %}" class="rounded-md bg-primary py-2 px-4 border border-transparent text-center text-sm text-white transition-all shadow-md hover:bg-secondary" type="button">
                        Read more
                      </a>
                    </div>
                  </div>  
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ posts.title }}
{% endblock %}
{% block content %}
<style>

</style>
<section class="font-title px-4 md:px-4 2xl:px-0 bg-cover bg-no-repeat w-full h-80" 
         style="background-image: url({% static 'images/page-title.jpg' %});">
    <div class="max-w-screen-xl mx-auto h-full flex flex-col justify-center gap-3">
        <h3 class="text-white font-medium text-sm md:text-base uppercase">Blog / {{ posts.title }}</h3>
        <h1 class="text-white text-2xl md:text-4xl font-bold">{{ posts.title }}</h1>
    </div>
</section>
<section class="font-title mt-20 px-4 md:px-4 2xl:px-0">
    <div class="max-w-screen-xl mx-auto flex flex-col gap-10 md:flex-row justify-start"> 
        <div class="w-full md:w-3/4">
            <div class="mb-10 h-[350px] ">
                <img src="{{ posts.image.url }}" alt="Blog Image" 
                     class="w-full h-full  object-cover rounded-lg">
            </div>
            <div class="mt-10">
                <h1 class="text-3xl font-bold mb-5">{{ posts.title }}</h1>
                <div class="bg-white blog_details leading-relaxed">
                    {{ posts.long_desc | safe }}
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/4">
        <div class="w-full p-6 border border-gray-200 rounded-lg bg-gray-100">
            <h3 class="text-primary text-2xl font-bold">Related Posts</h3>
            {% for item in related_post %}
            {% if item.slug != posts.slug %}
             <a href="{% url 'blog:blog_details' item.slug %}">
            <div class="flex justify-between items-center p-3 mt-6 text-body rounded-lg hover:bg-secondary hover:text-white">
             <h4 class=" font-medium text-base">{{item.title}}</h4>
            <i class="fa text-base fa-arrow-right text-right"></i>
            </div>
             </a>
             {% endif %}
           {% endfor %}
           </div>
    </div>
</div>
</section>
{% endblock %}